file:C:/Users/madhe/Documents/software/Git/etc/gitconfig	diff.astextplain.textconv=astextplain
file:C:/Users/madhe/Documents/software/Git/etc/gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:C:/Users/madhe/Documents/software/Git/etc/gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Users/madhe/Documents/software/Git/etc/gitconfig	filter.lfs.process=git-lfs filter-process
file:C:/Users/madhe/Documents/software/Git/etc/gitconfig	filter.lfs.required=true
file:C:/Users/madhe/Documents/software/Git/etc/gitconfig	http.sslbackend=schannel
file:C:/Users/madhe/Documents/software/Git/etc/gitconfig	core.autocrlf=true
file:C:/Users/madhe/Documents/software/Git/etc/gitconfig	core.fscache=true
file:C:/Users/madhe/Documents/software/Git/etc/gitconfig	core.symlinks=false
file:C:/Users/madhe/Documents/software/Git/etc/gitconfig	pull.rebase=false
file:C:/Users/madhe/Documents/software/Git/etc/gitconfig	credential.helper=manager
file:C:/Users/madhe/Documents/software/Git/etc/gitconfig	credential.https://dev.azure.com.usehttppath=true
file:C:/Users/madhe/Documents/software/Git/etc/gitconfig	init.defaultbranch=master
file:C:/Users/madhe/.gitconfig	user.email=madhesh.suguna76@gmail.com
file:C:/Users/madhe/.gitconfig	user.name=Madhesh767
file:C:/Users/madhe/.gitconfig	filter.lfs.required=true
file:C:/Users/madhe/.gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:C:/Users/madhe/.gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Users/madhe/.gitconfig	filter.lfs.process=git-lfs filter-process
file:.git/config	core.repositoryformatversion=0
file:.git/config	core.filemode=false
file:.git/config	core.bare=false
file:.git/config	core.logallrefupdates=true
file:.git/config	core.symlinks=false
file:.git/config	core.ignorecase=true
file:.git/config	remote.origin.url=https://github.com/Madhesh767/Ecart.git
file:.git/config	remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config	branch.main.remote=origin
file:.git/config	branch.main.merge=refs/heads/main
file:.git/config	branch.main.vscode-merge-base=origin/main
file:.git/config	branch.Mad.remote=origin
file:.git/config	branch.Mad.merge=refs/heads/Mad
file:.git/config	branch.Mad.vscode-merge-base=origin/Mad
